# Generated by Django 3.2.23 on 2026-01-18 22:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Номер')),
                ('room_type', models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('triple', 'Трехместный')], max_length=10, verbose_name='Тип номера')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость за сутки')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('fire_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
            ],
            options={
                'verbose_name': 'Служащий',
                'verbose_name_plural': 'Служащие',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('check_in_date', models.DateField(verbose_name='Дата заселения')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='Дата выселения')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guests', to='api.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этаж')),
                ('weekday', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.staff', verbose_name='Служащий')),
            ],
            options={
                'verbose_name': 'Расписание уборки',
                'verbose_name_plural': 'Расписания уборки',
                'ordering': ['weekday', 'floor'],
            },
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['passport_number'], name='api_guest_passpor_c0515c_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['city'], name='api_guest_city_b3c4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='api_guest_check_i_b0f819_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningschedule',
            index=models.Index(fields=['floor', 'weekday'], name='api_cleanin_floor_4c47d8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cleaningschedule',
            unique_together={('staff', 'floor', 'weekday')},
        ),
    ]
